### ISSUE TITLE
[normalize] Asking the same object in the same operation with less fields results in a failure to cache the operation

### ISSUE THREAD

**Issue by iscriptology** [gql-dart/ferry#98]
I'll explain this bug with an example:
```graphql
type Person implements Node {
    id: ID!
    firstName: String!
    lastName: String!
}

type Message implements Node {
    id: ID!
    content: String!
    sender: Person!
}

type Viewer implements Node {
    id: ID!
    friends: [Person!]!
    latestMessage: Message!
}

type Query {
    viewer: Viewer!
}
```

And let's say in the main screen of my app I want to display a list of friends (first name + last name) and my latest message: (only first name is shown in the sender line of messages on my app)
```graphql
query FetchMainScreen {
    viewer {
        friends {
            id
            firstName
            lastName
        }
        latestMessage {
            id
            content
            sender {
                id
                firstName
            }
        }
    }
}
```

When I fetch this query the first time: `_client.responseStream(GFetchMainScreenReq())` using a cache-enabled fetch policy, it will write the normalized data to the cache. But during this process it will **override** one sender with only firstName attached to it. (because the latestMessage's sender is parsed _after_ the friends list, and it only contains firstName)

So if I run `_client.cache.readQuery(GFetchMainScreenReq())` immediately after it will return null because a `PartialDataException` is raised.

This can't be right, as I just executed this query, and now it's by-design stays _partial_ in the cache.

If, say, I rewrite the query above like that: (latestMessage first, friends after)
```graphql
query FetchMainScreen {
    viewer {
        latestMessage {
            id
            content
            sender {
                id
                firstName
            }
        }
        friends {
            id
            firstName
            lastName
        }
    }
}
```
The cache works as expected (since the overwrite just added a lastName field to the sender)

The source of this issue to my understanding is at `normalize_node.dart:75`

```dart
        if (fieldPolicy?.merge != null) {
          return data
            ..[fieldName] = fieldPolicy.merge(
              existingFieldData,
              fieldData,
              FieldFunctionOptions(
                field: field,
                config: config,
              ),
            );
        }
        // ->>>>>>>>> This overrides the previous person that was normalized in this operation with less complete data.
        return data..[fieldName] = fieldData; 
```

I would suggest implementing a default deepMerge (as indeed happens in across-queries writes to the cache) even if I didn't implement a custom merge in a field policy.

**Comment by smkhalsa** [comment]
Thanks @iscriptology. 

https://github.com/gql-dart/ferry/pull/100 should fix this issue. Can you please confirm?

**Comment by iscriptology** [comment]
The problem persists.

Somehow the write method is called twice - once with the full object and then with the partial object.

I'm not exactly sure how it happened.

1. Maybe you should incorporate `existingFieldData` so data is not overwritten?
2. Something that will surely solve it would be to replace 
`write: (dataId, value) => normalizedResult[dataId] = value,` (`cache.dart:127`)
with something that will not override the pre-existing objects if they are there. (again, deepmerge)

**Comment by iscriptology** [comment]
Thanks for the quick response <3

**Comment by smkhalsa** [comment]
Can you add a failing test case?

**Comment by iscriptology** [comment]
I'll try later today
